services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\AdmiralCloudConnector\:
    resource: '../Classes/*'

  CPSIT\AdmiralCloudConnector\EventListener\InstallListener:
    tags:
      - name: event.listener
        method: createAdmiralCloudFileStorage
        identifier: 'admiral-cloud-connector/install-listener'
