name: Release
on:
  push:
    tags:
      - '*'

env:
  REF_NAME: ${{ github.ref_name }}

jobs:
  # Job: Create release
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      release-notes-url: ${{ steps.create-release.outputs.url }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ "$REF_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            exit 1
          fi

      # Create release
      - name: Create release
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          url="$(gh release create "$REF_NAME" --generate-notes)"
          echo "url=$url" >> "$GITHUB_OUTPUT"

  # Job: Publish on TER
  ter-publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [release]
    runs-on: ubuntu-latest
    env:
      TYPO3_EXTENSION_KEY: admiral_cloud_connector
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
      TYPO3_EXCLUDE_FROM_PACKAGING: packaging_exclude.php
      RELEASE_NOTES_URL: ${{ needs.release.outputs.release-notes-url }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ "$REF_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            exit 1
          fi

      # Prepare version
      - run: echo "RELEASE_COMMENT=See release notes at ${RELEASE_NOTES_URL}" >> $GITHUB_ENV

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: 8.5
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2, typo3/tailor
          coverage: none

      - name: Reset files
        run: git reset --hard HEAD && git clean -dfx

      # Release
      - name: Publish to TER
        run: |
          php ~/.composer/vendor/bin/tailor set-version "$REF_NAME"
          php ~/.composer/vendor/bin/tailor ter:publish --comment "$RELEASE_COMMENT" "$REF_NAME"
